### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by Al3n70rn** [chrisadamsonmcri/CCSegThickness#3]
Hi,

I am not able to use 

CCSegProcess --do-seg --save-graphics

I have tried different nifti files from different subjects and I always obtain these errors :

CCSeg Error: too many values to unpack, subject /home/aalentorn/Downloads/CCSeg_ex/PCNSL_BabinetT1POST
Traceback (most recent call last):
  File "./CCSegProcess", line 237, in main
    CCSegPipeSeg.segCC(outputBase, doGraphics = doGraphics, doLK = segLK, segNoAuto = segNoAuto, segChooseFirst = segChooseFirst, segGridInitPoints = segGridInitPoints)
  File "/home/aalentorn/.local/share/Trash/files/CCSegThickness_20170810/CCSegPipeSeg.py", line 1325, in segCC
    Distances, TangentDots = nearestAnglesDistances(templateBasedCCSeg, LKCCSeg[z])
  File "/home/aalentorn/.local/share/Trash/files/CCSegThickness_20170810/CCSegPipeSeg.py", line 479, in nearestAnglesDistances
    templateSegContours, hierarchy = cv2.findContours(numpy.uint8(templateSegMask), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack
None

By the way, when I use 

CCSegProcess --do-seg --save-graphics --seg-no-auto

and then I obtain a _seg.hdf5 file, I have the same issue with 

CCSegProcess --do-thickness --save-graphics

CCSeg Thickness Error: too many values to unpack, subject /home/aalentorn/Downloads/CCSeg_ex/PCNSL_BabinetT1POST
Traceback (most recent call last):
  File "./CCSegProcess", line 269, in main
    CCSegPipeThickness.thicknessCC(outputBase, doGraphics = doGraphics, thicknessNoReg = thicknessNoReg)
  File "/home/aalentorn/.local/share/Trash/files/CCSegThickness_20170810/CCSegPipeThickness.py", line 439, in thicknessCC
    finalSegContours, hierarchy = cv2.findContours(numpy.uint8(finalSeg), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack
None

I am able to use CCSegManedit and save _seg_manedit.hdf5 file, but when I use 

CCSegProcess --do-thicknessmanedit --save-graphics

I also have the same issue:

CCSeg Thickness Error: too many values to unpack

Do you have any idea of what am I doing wrong ?

**Comment by chrisadamsonmcri** [comment]
Apologies for not looking at this, I will get to this soon.

**Comment by Al3n70rn** [comment]
Hi,

Just an update, I tested again with the new version and it works! Thanks!

Best regards and happy new year!
